// This file was generated by prisma-field-encryption.

import type { PrismaClient, CompensationDetails } from '@prisma/client'
import {
  ProgressReportCallback,
  defaultProgressReport,
  visitRecords
} from 'prisma-field-encryption/dist/generator/runtime'

type Cursor = CompensationDetails['id']

export async function migrate(
  client: PrismaClient,
  reportProgress: ProgressReportCallback = defaultProgressReport
): Promise<number> {
  return visitRecords<PrismaClient, Cursor>({
    modelName: 'CompensationDetails',
    client,
    getTotalCount: client.compensationDetails.count,
    migrateRecord,
    reportProgress,
  })
}

async function migrateRecord(client: PrismaClient, cursor: Cursor | undefined) {
  return await client.$transaction(async tx => {
    const record = await tx.compensationDetails.findFirst({
      take: 1,
      skip: cursor === undefined ? undefined : 1,
      ...(cursor === undefined
        ? {}
        : {
            cursor: {
              id: cursor
            }
          }),
      orderBy: {
        id: 'asc'
      },
      select: {
        id: true,
        currency: true,
        salary_ctc: true,
        breakdown: true
      }
    })
    if (!record) {
      return cursor
    }
    await tx.compensationDetails.update({
      where: {
        id: record.id
      },
      data: {
        currency: record.currency,
        salary_ctc: record.salary_ctc,
        breakdown: record.breakdown
      }
    })
    return record.id
  })
}

/**
 * Internal model:
 * {
 *   "cursor": "id",
 *   "fields": {
 *     "currency": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     },
 *     "salary_ctc": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     },
 *     "breakdown": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     }
 *   },
 *   "connections": {
 *     "employee": {
 *       "modelName": "Employee",
 *       "isList": false
 *     }
 *   }
 * }
 */
