// This file was generated by prisma-field-encryption.

import type { PrismaClient, Employee } from '@prisma/client'
import {
  ProgressReportCallback,
  defaultProgressReport,
  visitRecords
} from 'prisma-field-encryption/dist/generator/runtime'

type Cursor = Employee['id']

export async function migrate(
  client: PrismaClient,
  reportProgress: ProgressReportCallback = defaultProgressReport
): Promise<number> {
  return visitRecords<PrismaClient, Cursor>({
    modelName: 'Employee',
    client,
    getTotalCount: client.employee.count,
    migrateRecord,
    reportProgress,
  })
}

async function migrateRecord(client: PrismaClient, cursor: Cursor | undefined) {
  return await client.$transaction(async tx => {
    const record = await tx.employee.findFirst({
      take: 1,
      skip: cursor === undefined ? undefined : 1,
      ...(cursor === undefined
        ? {}
        : {
            cursor: {
              id: cursor
            }
          }),
      orderBy: {
        id: 'asc'
      },
      select: {
        id: true,
        contact_number: true,
        address: true
      }
    })
    if (!record) {
      return cursor
    }
    await tx.employee.update({
      where: {
        id: record.id
      },
      data: {
        contact_number: record.contact_number,
        address: record.address
      }
    })
    return record.id
  })
}

/**
 * Internal model:
 * {
 *   "cursor": "id",
 *   "fields": {
 *     "contact_number": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     },
 *     "address": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     }
 *   },
 *   "connections": {
 *     "compensation_details": {
 *       "modelName": "CompensationDetails",
 *       "isList": true
 *     },
 *     "statutory_details": {
 *       "modelName": "StatutoryDetails",
 *       "isList": true
 *     },
 *     "exit_details": {
 *       "modelName": "ExitDetails",
 *       "isList": true
 *     },
 *     "documents": {
 *       "modelName": "EmployeeDocument",
 *       "isList": true
 *     }
 *   }
 * }
 */
