// This file was generated by prisma-field-encryption.

import type { PrismaClient, ExitDetails } from '@prisma/client'
import {
  ProgressReportCallback,
  defaultProgressReport,
  visitRecords
} from 'prisma-field-encryption/dist/generator/runtime'

type Cursor = ExitDetails['id']

export async function migrate(
  client: PrismaClient,
  reportProgress: ProgressReportCallback = defaultProgressReport
): Promise<number> {
  return visitRecords<PrismaClient, Cursor>({
    modelName: 'ExitDetails',
    client,
    getTotalCount: client.exitDetails.count,
    migrateRecord,
    reportProgress,
  })
}

async function migrateRecord(client: PrismaClient, cursor: Cursor | undefined) {
  return await client.$transaction(async tx => {
    const record = await tx.exitDetails.findFirst({
      take: 1,
      skip: cursor === undefined ? undefined : 1,
      ...(cursor === undefined
        ? {}
        : {
            cursor: {
              id: cursor
            }
          }),
      orderBy: {
        id: 'asc'
      },
      select: {
        id: true,
        exit_reason: true
      }
    })
    if (!record) {
      return cursor
    }
    await tx.exitDetails.update({
      where: {
        id: record.id
      },
      data: {
        exit_reason: record.exit_reason
      }
    })
    return record.id
  })
}

/**
 * Internal model:
 * {
 *   "cursor": "id",
 *   "fields": {
 *     "exit_reason": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     }
 *   },
 *   "connections": {
 *     "employee": {
 *       "modelName": "Employee",
 *       "isList": false
 *     }
 *   }
 * }
 */
