// This file was generated by prisma-field-encryption.

import type { PrismaClient } from '@prisma/client'
import { migrate as migrateEmployee } from './Employee'
import { migrate as migrateCompensationDetails } from './CompensationDetails'
import { migrate as migrateStatutoryDetails } from './StatutoryDetails'
import { migrate as migrateExitDetails } from './ExitDetails'
import { migrate as migrateActivityLog } from './ActivityLog'

export interface ProgressReport {
  model: string
  processed: number
  totalCount: number
  performance: number
}

export type ProgressReportCallback = (
  progress: ProgressReport
) => void | Promise<void>

export const defaultProgressReport: ProgressReportCallback = ({
  model,
  totalCount,
  processed,
  performance
}) => {
  const length = totalCount.toString().length
  const pct = Math.round((100 * processed) / totalCount)
    .toString()
    .padStart(3)
  console.info(
    `${model.padEnd(19)} ${pct}% processed ${processed
      .toString()
      .padStart(length)} / ${totalCount} (took ${performance.toFixed(2)}ms)`
  )
}

// --

export type MigrationReport = {
  Employee: number,
  CompensationDetails: number,
  StatutoryDetails: number,
  ExitDetails: number,
  ActivityLog: number
}

/**
 * Migrate models sequentially.
 *
 * Processed models:
 * - Employee
 * - CompensationDetails
 * - StatutoryDetails
 * - ExitDetails
 * - ActivityLog
 *
 * @returns a dictionary of the number of processed records per model.
 */
export async function migrate(
  client: PrismaClient,
  reportProgress: ProgressReportCallback = defaultProgressReport
): Promise<MigrationReport> {
  const processedEmployee = await migrateEmployee(client, reportProgress)
  const processedCompensationDetails = await migrateCompensationDetails(client, reportProgress)
  const processedStatutoryDetails = await migrateStatutoryDetails(client, reportProgress)
  const processedExitDetails = await migrateExitDetails(client, reportProgress)
  const processedActivityLog = await migrateActivityLog(client, reportProgress)
  return {
    Employee: processedEmployee,
    CompensationDetails: processedCompensationDetails,
    StatutoryDetails: processedStatutoryDetails,
    ExitDetails: processedExitDetails,
    ActivityLog: processedActivityLog
  }
}
