// This file was generated by prisma-field-encryption.

import type { PrismaClient, StatutoryDetails } from '@prisma/client'
import {
  ProgressReportCallback,
  defaultProgressReport,
  visitRecords
} from 'prisma-field-encryption/dist/generator/runtime'

type Cursor = StatutoryDetails['id']

export async function migrate(
  client: PrismaClient,
  reportProgress: ProgressReportCallback = defaultProgressReport
): Promise<number> {
  return visitRecords<PrismaClient, Cursor>({
    modelName: 'StatutoryDetails',
    client,
    getTotalCount: client.statutoryDetails.count,
    migrateRecord,
    reportProgress,
  })
}

async function migrateRecord(client: PrismaClient, cursor: Cursor | undefined) {
  return await client.$transaction(async tx => {
    const record = await tx.statutoryDetails.findFirst({
      take: 1,
      skip: cursor === undefined ? undefined : 1,
      ...(cursor === undefined
        ? {}
        : {
            cursor: {
              id: cursor
            }
          }),
      orderBy: {
        id: 'asc'
      },
      select: {
        id: true,
        bank_name: true,
        account_number: true,
        ifsc_code: true,
        pan_number: true,
        aadhar_number: true,
        pf_number: true
      }
    })
    if (!record) {
      return cursor
    }
    await tx.statutoryDetails.update({
      where: {
        id: record.id
      },
      data: {
        bank_name: record.bank_name,
        account_number: record.account_number,
        ifsc_code: record.ifsc_code,
        pan_number: record.pan_number,
        aadhar_number: record.aadhar_number,
        pf_number: record.pf_number
      }
    })
    return record.id
  })
}

/**
 * Internal model:
 * {
 *   "cursor": "id",
 *   "fields": {
 *     "bank_name": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     },
 *     "account_number": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     },
 *     "ifsc_code": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     },
 *     "pan_number": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     },
 *     "aadhar_number": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     },
 *     "pf_number": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     }
 *   },
 *   "connections": {
 *     "employee": {
 *       "modelName": "Employee",
 *       "isList": false
 *     }
 *   }
 * }
 */
